kind: Service
apiVersion: v1
metadata:
  name: pihole-web-service
  namespace : pihole-lox
spec:
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name : web
  - protocol: TCP
    port: 443
    targetPort: 443
    name : web-ssl
  - protocol: TCP
    port: 53
    targetPort: 53
    name : dns-ssl
  loadBalancerIP: 10.99.2.221
  type: LoadBalancer 
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-service
  namespace: pihole-lox
spec:
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name : dns
  loadBalancerIP: 10.99.2.220
  type: LoadBalancer 
